name: 'Ghost Publish Action'
author: 'Rohit <@milliondreams>'

description: 'Publishes markdown to Ghost as post draft'
inputs:
  ghost_api_url:
    description: 'Ghost API URL'
    required: true
  ghost_admin_api_key:
    description: 'Ghost Admin API Key'
    required: true
runs:
  using: 'node16'
  main: 'index.js'

